# Generated by Django 5.0.6 on 2024-10-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemrole',
            name='permissions',
        ),
        migrations.AddField(
            model_name='systemrole',
            name='permissions',
            field=models.ManyToManyField(related_name='role_permissions', to='user_management.systempermission'),
        ),
    ]
