# Generated by Django 5.0.6 on 2024-10-10 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0004_alter_serviceprovider_church_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MchangoPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inserted_by', models.CharField(max_length=255)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mchango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.mchango')),
                ('mhumini', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_providers.wahumini')),
            ],
        ),
    ]
