# Generated by Django 5.0.6 on 2024-10-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0005_mchangopayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mchango',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mchango',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
