# Generated by Django 5.0.6 on 2024-10-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0007_ahadi_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='budget',
            field=models.DecimalField(decimal_places=4, default=100000.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='mchango',
            name='mchango_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='mchangopayments',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
