# Generated by Django 5.0.6 on 2024-10-14 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0009_alter_ahadi_amount_alter_ahadi_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jumuiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.TextField(blank=True, null=True)),
                ('jina_kiongozi', models.CharField(max_length=300)),
                ('namba_ya_simu', models.CharField(blank=True, max_length=12, null=True)),
                ('location', models.CharField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.serviceprovider')),
            ],
        ),
        migrations.AddField(
            model_name='wahumini',
            name='jumuiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_providers.jumuiya'),
        ),
        migrations.CreateModel(
            name='Kanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.TextField(blank=True, null=True)),
                ('jina_kiongozi', models.CharField(max_length=300)),
                ('namba_ya_simu', models.CharField(blank=True, max_length=12, null=True)),
                ('location', models.CharField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.serviceprovider')),
            ],
        ),
        migrations.AddField(
            model_name='jumuiya',
            name='kanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_providers.kanda'),
        ),
    ]
