# Generated by Django 5.0.6 on 2024-11-06 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0013_spmanagers_spmanagers_unique_user_church_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mchangopayments',
            name='payment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service_providers.paymenttype'),
        ),
        migrations.CreateModel(
            name='AhadiPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('inserted_by', models.CharField(max_length=255)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ahadi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.ahadi')),
                ('mhumini', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_providers.wahumini')),
                ('payment_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service_providers.paymenttype')),
            ],
        ),
    ]
