# Generated by Django 5.0.6 on 2024-11-11 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0014_mchangopayments_payment_type_ahadipayments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttypetransfer',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='paymenttypetransfer',
            name='from_payment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='service_providers.paymenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttypetransfer',
            name='to_payment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='service_providers.paymenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenue',
            name='payment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service_providers.paymenttype'),
            preserve_default=False,
        ),
    ]
