# Generated by Django 5.0.6 on 2024-11-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0015_remove_paymenttypetransfer_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='revenue_type_record',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
