# Generated by Django 5.0.6 on 2024-11-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0017_wahumini_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='churh_image',
            field=models.FileField(blank=True, null=True, upload_to='campaign/images/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='churh_leader_image',
            field=models.FileField(blank=True, null=True, upload_to='campaign/images/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='churh_leader_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
