# Generated by Django 5.0.6 on 2024-11-25 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0018_serviceprovider_churh_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsnumber',
            name='card_no',
            field=models.CharField(db_index=True, help_text='Unique card number for identification.', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='SadakaTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.serviceprovider')),
            ],
        ),
        migrations.AddField(
            model_name='sadaka',
            name='sadaka_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_providers.sadakatypes'),
        ),
    ]
