# Generated by Django 5.0.6 on 2024-12-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cardsnumber',
            name='service_pro_mhumini_6dd26f_idx',
        ),
        migrations.AddField(
            model_name='cardsnumber',
            name='church',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service_providers.serviceprovider'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='cardsnumber',
            index=models.Index(fields=['mhumini', 'card_no', 'bahasha_type', 'church'], name='service_pro_mhumini_607043_idx'),
        ),
    ]
